#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-docker-libkv
Version  : 7283ef27ed32fe267388510a91709b307bb9942c
Release  : 3
URL      : https://github.com/docker/libkv/archive/7283ef27ed32fe267388510a91709b307bb9942c.tar.gz
Source0  : https://github.com/docker/libkv/archive/7283ef27ed32fe267388510a91709b307bb9942c.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 CC-BY-SA-4.0
BuildRequires : go
BuildRequires : golang-github-stretchr-testify

%description
# libkv
[![GoDoc](https://godoc.org/github.com/docker/libkv?status.png)](https://godoc.org/github.com/docker/libkv)
[![Build Status](https://travis-ci.org/docker/libkv.svg?branch=master)](https://travis-ci.org/docker/libkv)
[![Coverage Status](https://coveralls.io/repos/docker/libkv/badge.svg)](https://coveralls.io/r/docker/libkv)
[![Go Report Card](https://goreportcard.com/badge/github.com/docker/libkv)](https://goreportcard.com/report/github.com/docker/libkv)

%prep
%setup -q -n libkv-7283ef27ed32fe267388510a91709b307bb9942c

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/docker/libkv"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x github.com/docker/libkv

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/docker/libkv/libkv.go
/usr/lib/golang/src/github.com/docker/libkv/libkv_test.go
/usr/lib/golang/src/github.com/docker/libkv/store/boltdb/boltdb.go
/usr/lib/golang/src/github.com/docker/libkv/store/boltdb/boltdb_test.go
/usr/lib/golang/src/github.com/docker/libkv/store/consul/consul.go
/usr/lib/golang/src/github.com/docker/libkv/store/consul/consul_test.go
/usr/lib/golang/src/github.com/docker/libkv/store/etcd/etcd.go
/usr/lib/golang/src/github.com/docker/libkv/store/etcd/etcd_test.go
/usr/lib/golang/src/github.com/docker/libkv/store/helpers.go
/usr/lib/golang/src/github.com/docker/libkv/store/mock/mock.go
/usr/lib/golang/src/github.com/docker/libkv/store/store.go
/usr/lib/golang/src/github.com/docker/libkv/store/zookeeper/zookeeper.go
/usr/lib/golang/src/github.com/docker/libkv/store/zookeeper/zookeeper_test.go
/usr/lib/golang/src/github.com/docker/libkv/testutils/utils.go
